#!/usr/bin/python
##
## Created : Sat Aug 10 06:17:20 IST 2013
## SPDX-FileCopyrightText: 2013-2026 Sriram Karra <karra.etc@gmail.com>
## SPDX-License-Identifier: AGPL-3.0-only
##
## This file is part of ASynK

clean:
	rm -rf user_dir *~ *.bak temp.bbdb
