## -*- mode: python -*-
##
## Created       : Wed Nov 30 17:41:51 IST 2011
## Last Modified : Thu Dec 01 10:13:25 IST 2011
##
## This is the main build specification file used by pyinstaller to convert
## the Gout python files and packages into a single directory self contained
## windows executable.
##
## This file is a modified version of the gout.spec generated by executing
## pyinstaller's Configure.py. The first half have modifications, the rest do
## not. If you started with the source code and want to generate a
## distribution bundle, make sure you pay attention to Analysis and a.datas
## below

a = Analysis([os.path.join(HOMEPATH,'support\\_mountzlib.py'),
               os.path.join(HOMEPATH,'support\\useUnicode.py'),
               '..\\Gout\\gout.py'],
               pathex=['Z:\\sriramkarra On My Mac\\stuff\\code\\python\\pyinstaller-1.5.1',
                      '..\\Gout\\lib', '..\\Gout\\tools'])

a.datas += [('app_state.json',    '..\\Gout\\app_state.json.example', 'DATA'),
            ('app_state.ex.json', '..\\Gout\\app_state.json.example', 'DATA'),
            ('fields.json',       '..\\Gout\\fields.json',            'DATA'),
            ('README',            '..\\Gout\\README',                 'DATA'),
            ('sync.png',          '..\\Gout\\sync.png',               'DATA')]

## What is below is unchanged from what is output by a 'python Configure.py' output

pyz = PYZ(a.pure)
exe = EXE(pyz,
          a.scripts,
          exclude_binaries=1,
          name=os.path.join('build\\pyi.win32\\gout', 'gout.exe'),
          debug=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT( exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               name=os.path.join('dist', 'gout'))
