This file is a README for the 'carddav' branch. This file will be deleted
after this branch is merged with master.

The carddav branch is an experimental branch for a new datastore backend for
CardDAV servers. The idea is with this one can sync BBDB and MS Outlook
contacts to a CardDAV server.

* Status

** Thu Apr 04 19:21:33 IST 2013

   Able to (a) fetch a vcf file from server (b) parse and extract a few fields
   (like name, suffix etc.) from it, and (c) construct a contact object

   Also able to construct a simple CDContact objet, and then push it to the
   sever.

   That is some pretty good progress... but many things about UID management
   are not clear. For sake of convenience added a get_uid/set_uid pair for
   contact_cd.py, but this is not the right way to go. Need to understand how
   the vCard UID field is used And also figure out how it is to be used in
   synching.

** Thu Apr 04 13:27:53 IST 2013

   Able to read server side addressbook folders, fetch their contents, and
   construct the pimdb/folder/contact objects. Next step is to be able to
   parse the vCard files and construct Contacts objects from fetched contents.

** Tue Apr 02 19:39:42 IST 2013

   Discovered Apple's pretty decent caldavclientlibrary, which has
   webdav/caldav/carddav wrappers. It's going to make it easier to deal with
   the server, and we will at least work with Apple's Calendar server. Hooked
   up this guy with a simple test script and pimdb_cd.py is on its way! Humble
   beginning.

* Timelog

** Summary

#+BEGIN: clocktable :maxlevel 2 :scope file
Clock summary at [2013-04-04 Thu 19:28]

| L | Headline     | Time    |       |
|---+--------------+---------+-------|
|   | *Total time* | *12:47* |       |
|---+--------------+---------+-------|
| 1 | Timelog      | 12:47   |       |
| 2 | Clockings    |         | 12:47 |
#+END:

** Clockings
   CLOCK: [2013-04-04 Thu 18:21]--[2013-04-04 Thu 19:20] =>  0:59
   CLOCK: [2013-04-04 Thu 16:32]--[2013-04-04 Thu 17:01] =>  0:29
   CLOCK: [2013-04-04 Thu 14:10]--[2013-04-04 Thu 15:43] =>  1:33
   CLOCK: [2013-04-04 Thu 13:20]--[2013-04-04 Thu 13:25] =>  0:05
   CLOCK: [2013-04-04 Thu 11:28]--[2013-04-04 Thu 12:47] =>  1:19
   CLOCK: [2013-04-04 Thu 07:30]--[2013-04-04 Thu 08:24] =>  0:54
   CLOCK: [2013-04-03 Wed 18:51]--[2013-04-03 Wed 20:22] =>  1:31
   CLOCK: [2013-04-03 Wed 16:27]--[2013-04-03 Wed 17:36] =>  1:09
   CLOCK: [2013-04-03 Wed 05:29]--[2013-04-03 Wed 06:52] =>  1:23
   CLOCK: [2013-04-02 Tue 18:41]--[2013-04-02 Tue 19:42] =>  1:01
   CLOCK: [2013-04-02 Tue 17:47]--[2013-04-02 Tue 18:26] =>  0:39
   CLOCK: [2013-04-02 Tue 14:26]--[2013-04-02 Tue 15:21] =>  0:55
   CLOCK: [2013-04-02 Tue 12:58]--[2013-04-02 Tue 13:48] =>  0:50
