Created       : Wed Aug 24 22:41:42 IST 2011
Last Modified : Sun May 13 13:51:23 IST 2012

* Introduction

  ASynK - Awesome Sync (by Karra), is a flexible PIM synchronization platform
  written in Python. ASynK was earlier known as Gout. High level features
  include:

  - ASynK allows bidirectional sync of Contact across any pair of sources
    from: Google Contacts, Microsoft Outlook, and Emacs BBDB - what we call
    PIM DBs (for Personal Information Management Databases)

  - ASynK is the only two-way synchronization software for BBDB known to be in
    existence today. So if you are keen to keep BBDB content synchronized with
    a mobile device or Outlook, look no further.

  - ASynK works on Windows, MacOS X, and Linux

  - Synchronization is granular to the level of 'Folders', i.e. you can
    synchronize one folder of Google Contacts with a Outlook folder (on
    Windows at work, say), and another Google folder in the same account with
    BBDB (On your Mac, say)

  - The infrastructure is there to add more database and item types
    (i.e. tasks, notes, etc.), but currently only Contact synchronization for
    Google Contacts, BBDB and Outlook supported

  - It is free software, and released under the GNU AGPL version 3

* Getting It

   The official website for ASynK is at: http://karra-asynk.appspot.com You
   will find links to latest download, complete documentaiton, and other
   information on that website.

   The source code for ASynK is hosted on Github at:
   https://github.com/skarra/AsynK (earlier hosted at:
   https://github.com/skarra/Gout) Visit the site to grab the bleeding edge
   development version, or to register an issue you have identified.


