Created       : Wed Aug 24 22:41:42 IST 2011
Last Modified : Tue May 15 09:47:27 IST 2012

This is only a short introduction and some key points of interest. For more
details on how to use ASynK please refer to the included documentation, or the
official website for ASynK is at: http://karra-asynk.appspot.com You will find
links to latest download, complete documentaiton, and other information on
that website.

* About

  ASynK - Awesome Sync (by Karra), is a flexible PIM synchronization platform
  written in Python. ASynK was earlier known as Gout. High level features
  include:

  - ASynK allows bidirectional sync of Contact across any pair of sources
    from: Google Contacts, Microsoft Outlook, and Emacs BBDB - what we call
    PIM DBs (for Personal Information Management Databases)

  - ASynK is the only two-way synchronization software for BBDB known to be in
    existence today. So if you are keen to keep BBDB content synchronized with
    a mobile device or Outlook, look no further.

  - ASynK works on Windows, MacOS X, and Linux

  - Synchronization is granular to the level of 'Folders', i.e. you can
    synchronize one folder of Google Contacts with a Outlook folder (on
    Windows at work, say), and another Google folder in the same account with
    BBDB (On your Mac, say)

  - The infrastructure is there to add more database and item types
    (i.e. tasks, notes, etc.), but currently only Contact synchronization for
    Google Contacts, BBDB and Outlook supported

  - It is free software, and released under the GNU AGPL version 3

* Installation

** Dependencies

   - You need Python (tested with 2.7, try earlier versions at your
     descretion)

   - If you wish to sync to Outlook you can do that only on Windows. Further
     you will need MS Outlook installed, along with a third party python
     library called Pywin32 from Mark Hammond

** Building Documentation

   There is no build or installation required to use the main program. You can
   go the section on Usage below.

   If you wish to build the documentation from source, you will have to
   execute the following commands in order from the root directory, i.e where
   you have the configure.ac file

   - $ autoreconf
   - $ automake --add-missing
   - $ ./configure
   - $ make 

   You may have to install additional programs like makeinfo and other TeX
   related programs. 
   
   You will need autoconf (>2.64), automake (> 1.11) for the above to work.

** Usage

   Refer to the documentation. You could also start with 'python asynk.py -h'
   from the root directory of the downloaded source tree.
