Created : Wed Aug 24 22:41:42 IST 2011

This is only a short introduction and some key points of interest. For more
details on how to use ASynK please refer to the included documentation, or the
official website for ASynK is at: http://asynk.io/ You will find
links to latest download, complete documentation, and other information on
that website.

* About

  ASynK - Awesome Sync (by Karra), is a flexible Contacts synchronization platform
  written in Python. High level features include:

  - ASynK allows two-way sync of Contacts across any two supported sources -
    Google Contacts, any CardDAV server and Emacs BBDB. (Microsoft Outlook,
    Microsoft Exchange Server used to be supported but they remain broken for
    the moment)
  
  - You can use ASynK to copy contacts from one Google account to another
    (say from a Google Apps account at work to a personal address before you
    leave your job). You can do this at the level of folders (see below)

  - ASynK is the only two-way synchronization option for BBDB known to be in
    existence today. So if you are keen to keep your BBDB content synchronized
    with a mobile device or Outlook, look no further.
  
  - ASynK works on Windows, MacOS X, and Linux. Outlook synchronization
    only works on Windows
  
  - Synchronization is granular to the level of 'Folders', i.e. you can
    synchronize one folder of Google Contacts with a Outlook folder (on
    Windows at work, say), and another Google folder in the same account with
    BBDB (On your Mac, say)
  
  - The infrastructure is there to add more database and item types
    (i.e. tasks, notes, etc.), but currently only Contacts synchronization is
    supported.
    
  - It is free software, and released under the GNU AGPL (Affero GPL) version
    3

* Installation

** Fresh Installation

As you are reading this file, the most efficient installation is to
recursively clone this git repository to your machine. Then see the
section titled Usage below to invoke ASynK.

: git clone  --recursive https://github.com/skarra/ASynK.git

** Updating an earlier install

   If you are updating your ASynK installation from an earlier version,
   please note that many new git-submodules are added to the project. So for
   your update to work properly you need to update all
   sub-modules. Recommended way to do this would be to fun the following
   command from the root of your ASynK directory, after you pull in the latest
   changes

: git submodule update --init --recursive

** Setting up your Python environment

   ASynK is written in Python 3. For the best experience you will need Pythyon
   3.10 or later. There are many python packages dependencies that are
   captured in requirements.txt file. We recommend creating a separate
   virtualenv for keeping all the dependencies up to date.

: $ cd ASynK

: $ python3.10 -m venv venv

: $ source venv/bin/activate

: $ pip install -r requirements.txt

: $ python asynk.py --version # sanity test to make sure basic dependencies are in order

***   Other dependencies

   - If you wish to sync from/to MS Outlook (As of May 2026: does not work)
     - MS Windows
     - Python 3.x for Windows
     - MS Outlook
     - Pywin32 from Mark Hammond, available from
       http://sourceforge.net/projects/pywin32/

* Usage

   The recommended way to use ASynK is to first create your own 'sync profile'
   which specifies which folders and PIM DBs you want to keep in sync. Refer
   to the documentation for more details.

   For the really impatient, ASynK comes with two default sync profiles that
   kick in if no other profile is configured.

: $ python asynk.py --op=sync [--dry-run] [--log=debug]

   If you run the above command on Windows, the entire default outlook
   contacts folder will get synched to "My Contacts" on Google Contacts. (You
   will be prompted for your google username and password). 

   On any non-windows platform if you have a  ~/.bbdb will simply be "backed
   up" to /tmp/asynk.bbdb.

   For further usage help, try "python asynk.py -h"
