Created       : Wed Aug 24 22:41:42 IST 2011
Last Modified : Mon May 14 14:30:45 IST 2012

This is only a short introduction and some key points of interest. For more
details on how to use ASynK please refer to the included documentation, or the
official website for ASynK is at: http://karra-asynk.appspot.com You will find
links to latest download, complete documentaiton, and other information on
that website.

* About

  ASynK - Awesome Sync (by Karra), is a flexible PIM synchronization platform
  written in Python. ASynK was earlier known as Gout. High level features
  include:

  - ASynK allows bidirectional sync of Contact across any pair of sources
    from: Google Contacts, Microsoft Outlook, and Emacs BBDB - what we call
    PIM DBs (for Personal Information Management Databases)

  - ASynK is the only two-way synchronization software for BBDB known to be in
    existence today. So if you are keen to keep BBDB content synchronized with
    a mobile device or Outlook, look no further.

  - ASynK works on Windows, MacOS X, and Linux

  - Synchronization is granular to the level of 'Folders', i.e. you can
    synchronize one folder of Google Contacts with a Outlook folder (on
    Windows at work, say), and another Google folder in the same account with
    BBDB (On your Mac, say)

  - The infrastructure is there to add more database and item types
    (i.e. tasks, notes, etc.), but currently only Contact synchronization for
    Google Contacts, BBDB and Outlook supported

  - It is free software, and released under the GNU AGPL version 3

* Installation

** Dependencies

   - You need Python (tested with 2.7, try earlier versions at your
     descretion)

   - If you wish to sync to Outlook you can do that only on Windows. Further
     you will need MS Outlook installed, along with a third party python
     library called Pywin32 from Mark Hammond

   - Detailed documentation is avaialble in various formats on the project
     page and in the pre-packaged bundles. The source repository has the
     documentattion source in Texinfo format. If you wish to convert the .texi
     file to other formats you need a bunch of tools, including autoconf (>
     2.64), automake (> 1.11), and texi tools like texi2dvi, texi2html,
     etc. If you think it is too much, it probably is. Most people should not
     need this.

** Usage

   Refer to the documentation. You could also start with 'python asynk.py -h'
   from the root directory of the downloaded source tree.
