.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2013 Cyril Bouthors <cyb@debian.org>,
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH ASYNK 1 "May 21, 2013"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
asynk \- Bi-directional synchronization for Google Contacts, BBDB and Outlook
.SH DESCRIPTION
This manual page documents briefly the
.B asynk
command. For more information, please read the online documentation at
https://karra-asynk.appspot.com/
