
* Cmdline checks

 ./asynk.py --op=create-profile --db gc gc  --folder \
 'http://www.google.com/m8/feeds/groups/karra.etc%40gmail.com/base/2fae451c0fe771d5'\
 'default' --store karra.etc karra.etc --name gcgctest --user-dir=/tmp

 ./asynk.py --op=create-profile --db cd cd  --store http://baikal/card.php/ \
 localhost:8008 --folder 'default' 'default' --name testcdcd --user-dir=~/.asynk.cd

  ./asynk.py --op=sync --dry-run --name gcgctest --user-dir=/tmp
  ./asynk.py --op=sync --name gcgctest --user-dir=/tmp
  ./asynk.py --op=sync --dry-run --name gcgctest --user-dir=/tmp --log=debug

* Core code flows documentation

** command line invocation

   asynk_cmdline.py: main()
   -> parse_args()
   -> alogger.setup()
   -> asynk = Asynk()
      -> self.validate_and_snarf_uinps()
         -> self._snarf_*
   -> asynk.dispatch()

* MS Exchange support

  Mon Jan 26 18:56:33 IST 2015: Not sure how many of these "Next things" are
  actually still pending.

** Next things to do

   - bulk clear sync tags
   - support --exuser and --expwd command line flags
   - support 'default' storeid to get URL through autodisc
   - support 'default' as foid

*** Fields that are not yet supported

    - postal addresses

** Log

*** Fri May 02 12:53:40 IST 2014

   The whole update items and sync state stuff is a bit messsed up. I think I
   tried to edit something and messed up the updateitems methods thiknking
   they are the sync_state method. So some damage needs to be undone.

*** Wed Apr 30 15:18:22 IST 2014

   Stuck with prep sync lists and stuff like that.

*** Fri Apr 18 18:56:34 IST 2014

   Able to create contacts with some of the standard field types. Now on to
   more complex, or 'Extended' Properties. (Done :)

*** Thu Apr 03 23:44:52 IST 2014

   New classes for Item and Contact to wrap around the EWS XML. Some problems
   with properly parsing and constructing those objects. Need to look into it.

*** Sun Mar 30 18:35:00 IST 2014

   Able to discover all the contact folders and also create new ones.

*** Thu Mar 27 22:34:10 IST 2014

   After struggling with SUDS and a bunch of random assorted soap clients,
   decided to just go with direct http, and now I am able to fetch basic
   details from the server! Next steps - parsing the details as well as
   fetching more important info.

*** Sat Mar 15 17:17:01 IST 2014

   Developing the autodiscovery service is going to be a very difficult
   affair. There are many deployment scenaros possible as made clear in the
   documentation and there's no way to validate the code in all the
   scenarios. So for now the autodiscover code is incomplete and, well, a bit
   shoddy. Sorry.


* == Old Logs: ==

* Branch refactor-a (gc-gc refactor)

** Thu Jan 22 14:59:53 IST 2015

   Sent a request for beta testing the branch to asynk-users. Will merge to
   master and announce as rc

** Tue Jan 20 10:20:30 IST 2015

   Got the gc-gc sync working. Hurray!! 

   Next steps: Make sure BB:CD sync works as before as also some of the CD:CD
   stuff. Then send out a request to dev mailingn list asking for people to
   take this for a spin.

** Fri Nov 07 13:12:57 IST 2014

   Updated the main driver for --op=sync. There is one interesting blocker
   related to storing all sync tags. See the comments in
   _get_sync_tags_as_str in contact_bb.py for more details.

   Note Nov 10: this was fixed for all the other DBs as well.

** Thu Nov 06 12:22:11 IST 2014

   Still working on the migration of the asynk_core.py so all the ops work
   with the Collections refactor. Today I migrated many of the operations -
   mostly the less important ones. 

   Next up - the last of the heavy weight operations - sync

** Sun Nov 02 09:46:43 IST 2014

   The branch is to enable multiple collections on the same type of db. There
   are some restrictions on that today. This branch is for some much needed
   refactoring to enable that

   The first goal will be to get a BBDB-BBDB sync going. For the other stuff
   we will need to work around the authentication stuff.

   Status as of now:

   ./asynk_cmdline.py --help works
   ./asynk_cmdline.py --op=list-folders --db=bb --store ~/.bbdb needs to be
   checked
   Nothing involving any of the other dbs will even work

* Other

** Fri Aug 09 18:29:39 IST 2013

   Started work on recovering from parsing errors during making lists... -
   https://github.com/skarra/ASynK/issues/37

   This has many parts:

   a) While building the lists we need to track a new category of contacts -
      those that had an error. 

   b) Then treat these errors differently.

   c) Identify there have been errors, and treat them differently.
